services:
  backend:
    build: .
    restart: unless-stopped
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - MYSQL_ROOT_PASSWORD=KfJGIEdcHUHpMYan4nKpDfxTyBTb4QmALutE5zFGUfL4D2ieaQwHGNP3R7GzlYNH
      - FRAPPE_SITE_NAME_HEADER=is.cctug.com
    volumes:
      - 'sites:/home/frappe/frappe-bench/sites'
      - 'logs:/home/frappe/frappe-bench/logs'
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
  frontend:
    build: .
    restart: unless-stopped
    command: nginx-entrypoint.sh
    expose:
      - '8080'
    environment:
      - 'BACKEND=backend:8000'
      - 'SOCKETIO=websocket:9000'
      - FRAPPE_SITE_NAME_HEADER=is.cctug.com
      - UPSTREAM_REAL_IP_ADDRESS=127.0.0.1
      - PROXY_READ_TIMEOUT=120
      - CLIENT_MAX_BODY_SIZE=50m
    volumes:
      - 'sites:/home/frappe/frappe-bench/sites'
      - 'logs:/home/frappe/frappe-bench/logs'
    depends_on:
      - backend
      - websocket
  websocket:
    build: .
    restart: unless-stopped
    command: 'node /home/frappe/frappe-bench/apps/frappe/socketio.js'
    volumes:
      - 'sites:/home/frappe/frappe-bench/sites'
      - 'logs:/home/frappe/frappe-bench/logs'
  queue-short:
    build: .
    restart: unless-stopped
    command: 'bench worker --queue short,default'
    volumes:
      - 'sites:/home/frappe/frappe-bench/sites'
      - 'logs:/home/frappe/frappe-bench/logs'
    depends_on:
      - redis-queue
  queue-long:
    build: .
    restart: unless-stopped
    command: 'bench worker --queue long,default'
    volumes:
      - 'sites:/home/frappe/frappe-bench/sites'
      - 'logs:/home/frappe/frappe-bench/logs'
    depends_on:
      - redis-queue
  scheduler:
    build: .
    restart: unless-stopped
    command: 'bench schedule'
    volumes:
      - 'sites:/home/frappe/frappe-bench/sites'
      - 'logs:/home/frappe/frappe-bench/logs'
  redis-cache:
    image: 'redis:alpine'
    restart: unless-stopped
    volumes:
      - 'redis-cache:/data'
  redis-queue:
    image: 'redis:alpine'
    restart: unless-stopped
    volumes:
      - 'redis-queue:/data'
  mariadb:
    image: 'mariadb:10.6'
    restart: unless-stopped
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--skip-character-set-client-handshake'
      - '--skip-innodb-read-only-compressed'
    environment:
      - MYSQL_ROOT_PASSWORD=KfJGIEdcHUHpMYan4nKpDfxTyBTb4QmALutE5zFGUfL4D2ieaQwHGNP3R7GzlYNH
    volumes:
      - 'mariadb-data:/var/lib/mysql'

volumes:
  sites: null
  logs: null
  redis-cache: null
  redis-queue: null
  mariadb-data: null
